<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Maven_Settings</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-05T13:45:42</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>43318f14-c637-4b31-8a98-99b3322467d2</testSuiteGuid>
   <testCaseLink>
      <guid>5018864d-b2e7-4443-b095-8adde8405026</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Maven/Individual Test Cases/Settings/Settings_Preferences_Dashboard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63d44c3f-7152-4ebe-b05a-43b164b70e89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0729cc5f-17fe-41d2-9310-20bef31b69ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>002fade9-af36-4011-b01c-d9f57ca79f5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Maven/Individual Test Cases/Settings/Settings_Preferences_MerchantsandPartners</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dda26c39-e9a0-4f88-bac8-eb7a32938e3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2703e527-1db4-403e-98fe-9becdf9c18ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4acc1668-d49a-4611-b139-b3ead353f17d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Maven/Individual Test Cases/Settings/Settings_Preferences_Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06cb3a05-da77-4907-86bd-f2ed1558a46e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac6d4e69-94b4-4130-873c-2d915b7579de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d3d8905-1441-4af6-8c9a-958289738015</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Maven/Individual Test Cases/Settings/Settings_Preferences_Transactions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3396bd67-ccd9-4036-a1b5-25cd571a8b4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>703b224a-40cb-4eac-991a-8fd34b519bed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1577d9f0-99c4-4820-b575-1e62cf455e49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Maven/Individual Test Cases/Settings/Settings_Preferences_Users</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>239ef47c-d7e3-40b7-84e0-c09e6a00106f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9854f805-0202-4689-802e-660eeada4195</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
