<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_StateProvinceRegion</name>
   <tag></tag>
   <elementGuidId>5a2e9d25-4647-489a-9f7e-4a68c1a229f8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>18c255b0-1bc5-4b62-8350-2b9eaffc0eda</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State/Province/Region</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper sub-nav-closed&quot;]/div[@class=&quot;mp-page&quot;]/div[@class=&quot;mp-page-body&quot;]/div[@class=&quot;mp-content&quot;]/div[2]/form[1]/div[@class=&quot;mp-content-section&quot;]/div[@class=&quot;mp-content-block col-sm-12 border-none&quot;]/div[@class=&quot;mp-block-body&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm-6 col-lg-3&quot;]/div[@class=&quot;form-group&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
