<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DescriptionName</name>
   <tag></tag>
   <elementGuidId>337d952e-e60b-4f12-8083-e58e0d6f4d63</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description/Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper sub-nav-closed&quot;]/div[@class=&quot;mp-page&quot;]/div[@class=&quot;mp-page-body&quot;]/div[@class=&quot;mp-content&quot;]/div[@class=&quot;mp-tab-body&quot;]/div[@class=&quot;mp-content-section&quot;]/div[@class=&quot;mp-content-block col-sm-12 mb-5&quot;]/div[@class=&quot;mp-block-body&quot;]/div[@class=&quot;mp-table-viewport mp-auth-token-table inline empty&quot;]/div[@class=&quot;mp-table&quot;]/div[@class=&quot;mp-table-header&quot;]/div[@class=&quot;mp-table-row&quot;]/div[@class=&quot;mp-table-data ASC name&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
