<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_more_vert</name>
   <tag></tag>
   <elementGuidId>3b188965-d152-4994-879f-f44893b67c87</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper sub-nav-closed&quot;]/div[@class=&quot;mp-page fixed-table&quot;]/div[@class=&quot;mp-page-body&quot;]/div[@class=&quot;mp-content&quot;]/div[@class=&quot;mp-table-viewport mp-merchant-table&quot;]/div[@class=&quot;mp-table&quot;]/div[@class=&quot;mp-table-body&quot;]/div[@class=&quot;mp-table-row visa sale&quot;]/div[@class=&quot;mp-table-data actions&quot;]/div[@class=&quot;center&quot;]/div[@class=&quot;dropdown&quot;]/div[1]/button[@class=&quot;btn btn-link btn-icon text-gray px-0&quot;]/i[@class=&quot;material-icons&quot;]</value>
   </webElementProperties>
</WebElementEntity>
