<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gift Transactions</name>
   <tag></tag>
   <elementGuidId>9a75f3c3-1601-46bc-8889-361cc4cb220f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Gift Transactions' or . = 'Gift Transactions')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/reports/gift-transactions#?startdate=4%2F23%2F2018%200:0&amp;enddate=4%2F23%2F2018%2023:59&amp;amount1=&amp;amount2=&amp;sources=Web,Desktop,Cloud,CSE,emergepay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gift Transactions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)/ul[@class=&quot;dropdown-menu&quot;]/li[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
