<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_CU</name>
   <tag></tag>
   <elementGuidId>232afdb0-2b18-4a51-b737-b6534439646c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/md-card[@class=&quot;md-default-theme&quot;]/md-card-content[1]/section[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/section[1]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-bordered table-hover fade report in&quot;]/thead[1]/tr[1]/th[12]</value>
   </webElementProperties>
</WebElementEntity>
