<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StateProvinceRegion</name>
   <tag></tag>
   <elementGuidId>74b6da1a-f3e6-418d-9680-4517aa2220f2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State/Province/Region</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper sub-nav-closed&quot;]/div[@class=&quot;mp-page&quot;]/div[@class=&quot;mp-page-body&quot;]/div[@class=&quot;mp-content&quot;]/div[2]/form[1]/div[@class=&quot;mp-content-section&quot;]/div[@class=&quot;mp-content-block col-sm-12 border-none&quot;]/div[@class=&quot;mp-block-body&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm-6 col-lg-3&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;Select is-clearable is-searchable Select--single&quot;]/div[@class=&quot;Select-control&quot;]</value>
   </webElementProperties>
</WebElementEntity>
